# 异步编程

单线程工作模式：负责执行代码的线程只有一个
优点：更安全更简单
缺点：耗时任务阻塞执行

## 同步模式--排队执行

anonymous匿名函数
调用栈：正在执行的工作表，记录正在做的事情

## 异步模式

不会等待这个任务的结束才会进行下一个任务，开启过后立即往后执行下一个任务
作用：让单线程的JavaScript语言同事处理大量的耗时任务

倒计时器：单独工作不会受js线程影响
消息队列：待办的工作表

EventLoop：负责监听调用栈和消息队列，一旦调用栈中所有的任务都已经结束，消息队列就会取出第一个回调函数压入调用栈

js执行引擎：就是先去做完调用栈中所有的任务，然后再通过事件循环从消息队列中取一个任务再去执行，以此类推。过程中还可以往消息队列中添加任务，进行排队等待事件循环。

各个环节没有执行循序

JavaScript是单线程的，但是浏览器不是单线程的，JavaScript调用的内部的API并不是单线程的

异步模式是指运行环境提供的API是以异步模式去工作，异步模式是下达这个任务的开始指令就会往下执行，代码不会在这一行等待结束，例如：setimeout

## 回调函数-所有异步编程方案的根基

回调函数：由调用者定义，交给执行者执行的函数

CommonJs社区提出了Promise的规范，在ES2015中被标准化，成为语言规范

promise：承诺状态明确了之后都会有相应的任务会被自动执行，一旦明确了结果之后就不可能会发生改变了

### 基本用法

webpack-dev-server 配合
html-webpack-plugin自动生成使用当前js的HTML文件，而且会有自动刷新

yarn webpack-dev-server 04-promise-simple.js --open

--open自动打开浏览器

即便promise中没有任务的异步操作，then方法仍然会进入异步队列中排队，要等待同步代码全部执行完成后才会执行

promise最大的优势就是可以进行链式调用

### promise的特点

- promise对象的then方法会返回一个全新的promise对象
- 后面的then方法就是在上一个then返回的Peomise注册回调
- 前面then方法中回调函数的返回值会作为后面then方法回调的参数
- 如果回调中返回的是Promise，那后面then方法的回调会等待他的结束
- 如果回调中没有返回任何值，默认返回的是undefined

### promise catch

在代码中明确捕获每一个错误，而不是在全局统一处理

### promise 静态方法

- promise.resolve()快速的把一个值转为onFullfilled的promise对象,如果传入的是一个字符串，则它的onFullfilled拿到的参数就是字符串

  ```js
    Promise.resolve('foo').then((value)=>{
    console.log(value)
    })
    //完全等价于
    new Promise((resolve,reject)=>{
        resolve('foo')
    }).then((value)=>{
        console.log(value)
    })
  ```

- 如果promise.resolve()里面是另一个promise对象那这个对象会被原样返回
  
  ```js
  var promise = ajax('/api/users.json')
  var promise2 = Promise.resolve(promise)
  console.log(promise===promise2)
  ```

- 如果promise.resolve()传入的是一个包含then方法的对象,也就是说这个then中可以接收onFullfilled和onRejected两个回调，调用onFullfilled然后传入一个值，这样也可以作为一个promise被执行，那有这种then方法的对象是实现了一个叫做thenable的接口，也就是说这是一个可以被then的对象

> 接收这种对象的原因是,原生promise还没有被普及之前，很多时候都是使用第三方库去实现的promise，那把第三方的promise转为原生的promise就可以使用这种机制
  
  ```js
    Promise.resolve({
        then:(onFullfilled,onRejected)=>{
            onFullfilled('foo')
        }
    })
    .then((value)=>{
        console.log(value)
    })
  ```

- Promise.reject()只有一种失败的情况

```js
//不论传入什么值被捕获的都是一个失败的原因
Promise.reject(new Error('iii')).then((value)=>{
   console.log(value)
}).catch((error)=>{
    console.log(error)
})
```

### promise 并行

Promise.all()